defmodule RequestSeal.PropertySupport do
  @moduledoc false
  # Generated grammar and cryptographic checks derive from public specifications:
  # https://www.rfc-editor.org/rfc/rfc9651.html
  # https://www.rfc-editor.org/rfc/rfc9421.html#section-2.5
  # https://www.rfc-editor.org/rfc/rfc7515.html
  # https://www.rfc-editor.org/rfc/rfc7516.html
  # https://www.rfc-editor.org/rfc/rfc7517.html
  # https://www.rfc-editor.org/rfc/rfc8259.html
  import StreamData
  alias RequestSeal.{Body, Crypto, FieldOccurrence, Message, PublicKey, TransportFacts}
  alias RequestSeal.StructuredFields.{Schema, Value}

  def schema(type) do
    {:ok, schema} =
      Schema.new(%{
        revision: :rfc9651,
        type: type,
        item_types: Schema.types(:rfc9651),
        inner_lists: true
      })

    schema
  end

  def bare do
    one_of([
      map(integer(-999_999_999_999_999..999_999_999_999_999), &{:integer, &1}),
      map(integer(-999_999_999_999_999..999_999_999_999_999), &{:date, &1}),
      map(boolean(), &{:boolean, &1}),
      map(binary(max_length: 40), &{:bytes, &1}),
      map(string(:ascii, max_length: 40), &{:string, &1}),
      map(string(:alphanumeric, max_length: 40), &{:token, "a" <> &1}),
      map(string(:utf8, max_length: 20), &{:display_string, &1}),
      # Canonical decimal representations retain scale on parse/serialize.
      map(integer(-999_999_999..999_999_999), fn n ->
        {:decimal, {n * 10 + if(n < 0, do: -1, else: 1), 1}}
      end)
    ])
  end

  def parameters do
    map(list_of(bare(), max_length: 5), fn values ->
      values |> Enum.with_index() |> Enum.map(fn {value, i} -> {"p#{i}", value} end)
    end)
  end

  def item do
    bind(bare(), fn value ->
      map(parameters(), &%Value{type: :item, value: value, parameters: &1})
    end)
  end

  def member do
    one_of([
      item(),
      bind(list_of(item(), max_length: 5), fn items ->
        map(parameters(), &%Value{type: :inner_list, value: items, parameters: &1})
      end)
    ])
  end

  def value(:item), do: item()
  def value(:list), do: map(list_of(member(), max_length: 8), &%Value{type: :list, value: &1})

  def value(:dictionary) do
    map(list_of(member(), max_length: 8), fn values ->
      %Value{
        type: :dictionary,
        value: values |> Enum.with_index() |> Enum.map(fn {v, i} -> {"k#{i}", v} end)
      }
    end)
  end

  def change(bytes, index, mask \\ 1) do
    index = rem(index, byte_size(bytes))
    <<head::binary-size(^index), byte, tail::binary>> = bytes
    head <> <<Bitwise.bxor(byte, mask)>> <> tail
  end

  def message(value, target \\ "/path") do
    {:ok, field} = FieldOccurrence.new(%{name: "x-covered", value: value, section: :headers})
    {:ok, body} = Body.new(%{state: :unavailable})
    {:ok, transport} = TransportFacts.new(%{})

    {:ok, m} =
      Message.new(%{
        kind: :request,
        method: "POST",
        raw_target: target,
        target_form: :origin,
        scheme: "https",
        authority: "example.com",
        fields: [field],
        trailers: :unavailable,
        body: body,
        transport: transport
      })

    m
  end

  def keys do
    {ed, seed} = :crypto.generate_key(:eddsa, :ed25519)
    {point, scalar} = :crypto.generate_key(:ecdh, :secp256r1)
    {:ok, ed_public} = PublicKey.import({:ed25519, ed}, :raw)
    {:ok, ec_public} = PublicKey.import({:ec, "P-256", point}, :raw)

    [
      {"ed25519", {:ed25519, seed}, ed_public},
      {"ecdsa-p256-sha256", {:ec, "P-256", scalar}, ec_public}
    ]
  end

  def jose do
    [{_, material, public} | _] = keys()
    signer = fn alg, base -> Crypto.sign(alg, base, material) end

    jws = %{
      algorithms: ["EdDSA"],
      timeout: 5000,
      key_resolver: fn _ -> {:ok, %{algorithm: "EdDSA", key: public}} end
    }

    # Caller-owned custody holds the CEK generated by the real encryptor.
    {:ok, owner} = Agent.start_link(fn -> nil end)

    wrap = fn "dir", cek ->
      Agent.update(owner, fn _ -> cek end)
      {:ok, %{encrypted_key: "", header: %{}}}
    end

    jwe = %{
      algorithms: ["dir"],
      encryption: ["A256GCM"],
      max_plaintext: 1_048_576,
      timeout: 5000,
      key_resolver: fn _ ->
        {:ok,
         %{
           algorithm: "dir",
           unwrap: fn ek, h ->
             RequestSeal.JOSE.KeyManagement.unwrap("dir", ek, h, {:cek, Agent.get(owner, & &1)})
           end
         }}
      end
    }

    %{signer: signer, jws: jws, jwe: jwe, wrap: wrap, owner: owner}
  end

  def source(type, attrs \\ %{}) do
    {:ok, source} =
      RequestSeal.Discovery.Source.new(
        Map.merge(
          %{type: type, location: "https://example.com/", require_signed_directory: false},
          attrs
        )
      )

    source
  end

  def jwks(count) do
    keys =
      for _ <- 1..count do
        {point, _} = :crypto.generate_key(:eddsa, :ed25519)
        {:ok, key} = PublicKey.import({:ed25519, point}, :raw)
        {:ok, jwk} = PublicKey.export(key, :jwk)
        jwk
      end

    :json.encode(%{"keys" => keys}) |> IO.iodata_to_binary()
  end
end
